// dom-bench/App.jsx
import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
let counter = 1;
const mk = (start, n) => { const a = []; for (let i = 0; i < n; i++) a.push({ id: start + i, label: 'item ' + (start + i) }); return a; };
function App() {
  const [rows, setRows] = useState([]);
  const [selected, setSelected] = useState(0);
  const create = (n) => { const s = counter; counter += n; setRows(mk(s, n)); };
  const append = (n) => { const s = counter; counter += n; setRows(rs => rs.concat(mk(s, n))); };
  const update = () => setRows(rs => rs.map((r, i) => i % 10 === 0 ? { ...r, label: r.label + ' !!!' } : r));
  const swap = () => setRows(rs => { if (rs.length < 2) return rs; const a = rs.slice(); const t = a[1]; a[1] = a[a.length - 1]; a[a.length - 1] = t; return a; });
  const clear = () => { setRows([]); setSelected(0); };
  const remove = (id) => setRows(rs => rs.filter(r => r.id !== id));
  return (
    <div id="main">
      <button id="create" onClick={() => create(1000)}>create</button>
      <button id="create10k" onClick={() => create(10000)}>create10k</button>
      <button id="append" onClick={() => append(1000)}>append</button>
      <button id="update" onClick={update}>update</button>
      <button id="swap" onClick={swap}>swap</button>
      <button id="clear" onClick={clear}>clear</button>
      <table className="table"><tbody>
        {rows.map(r => (
          <tr key={r.id} className={r.id === selected ? 'danger' : ''}>
            <td className="col-md-1">{r.id}</td>
            <td className="col-md-4"><a onClick={() => setSelected(r.id)}>{r.label}</a></td>
            <td className="col-md-1"><a onClick={() => remove(r.id)}><span className="glyphicon glyphicon-remove"></span></a></td>
            <td className="col-md-6"></td>
          </tr>
        ))}
      </tbody></table>
    </div>
  );
}
createRoot(document.getElementById('app')).render(<App />);

// dom-bench/App.svelte
<script>
  let rows = []; let selected = 0; let counter = 1;
  const mk = (start, n) => { const a = []; for (let i = 0; i < n; i++) a.push({ id: start + i, label: 'item ' + (start + i) }); return a; };
  const create = (n) => { const s = counter; counter += n; rows = mk(s, n); };
  const append = (n) => { const s = counter; counter += n; rows = rows.concat(mk(s, n)); };
  const update = () => { rows = rows.map((r, i) => i % 10 === 0 ? { ...r, label: r.label + ' !!!' } : r); };
  const swap = () => { if (rows.length > 1) { const a = rows.slice(); const t = a[1]; a[1] = a[a.length - 1]; a[a.length - 1] = t; rows = a; } };
  const clear = () => { rows = []; selected = 0; };
  const remove = (id) => { rows = rows.filter(r => r.id !== id); };
</script>
<div id="main">
  <button id="create" on:click={() => create(1000)}>create</button>
  <button id="create10k" on:click={() => create(10000)}>create10k</button>
  <button id="append" on:click={() => append(1000)}>append</button>
  <button id="update" on:click={update}>update</button>
  <button id="swap" on:click={swap}>swap</button>
  <button id="clear" on:click={clear}>clear</button>
  <table class="table"><tbody>
    {#each rows as row (row.id)}
      <tr class={row.id === selected ? 'danger' : ''}>
        <td class="col-md-1">{row.id}</td>
        <td class="col-md-4"><a on:click={() => (selected = row.id)}>{row.label}</a></td>
        <td class="col-md-1"><a on:click={() => remove(row.id)}><span class="glyphicon glyphicon-remove"></span></a></td>
        <td class="col-md-6"></td>
      </tr>
    {/each}
  </tbody></table>
</div>
